Update cloudflare
update

diff --git a/cloudflare b/cloudflare
--- a/cloudflare
+++ b/cloudflare
@@ -1,47 +1,50 @@
-# A bash script to update a Cloudflare DNS A record with the external IP of the source machine
-# Used to provide DDNS service for my home
-# Needs the DNS record pre-creating on Cloudflare
+#!/usr/bin/env bash
+api_token=<CF token>
+email=<CF account email>
+zone_name=<DNS zone>
+dns_record=<A record FQDN>
 
-# Proxy - uncomment and provide details if using a proxy
-#export https_proxy=http://<proxyuser>:<proxypassword>@<proxyip>:<proxyport>
+set -e
 
-# Cloudflare zone is the zone which holds the record
-zone=example.com
-# dnsrecord is the A record which will be updated
-dnsrecord=www.example.com
+user_id=$(curl -s \
+	-X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
+	-H "Authorization: Bearer $api_token" \
+	-H "Content-Type:application/json" \
+	| jq -r '{"result"}[] | .id')
 
-## Cloudflare authentication details
-## keep this private
-cloudflare_token=<YOUR_CF_TOKEN_HERE>
+zone_id=$(curl -s \
+	-X GET "https://api.cloudflare.com/client/v4/zones?name=$zone_name&status=active" \
+	-H "Content-Type: application/json" \
+	-H "X-Auth-Email: $email" \
+	-H "Authorization: Bearer $api_token" \
+	| jq -r '{"result"}[] | .[0] | .id')
 
-# Get the current external IP address
-ip=$(curl -s -X GET https://checkip.amazonaws.com)
+record_data=$(curl -s \
+	-X GET "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records?type=A&name=$dns_record"  \
+	-H "Content-Type: application/json" \
+	-H "X-Auth-Email: $email" \
+	-H "Authorization: Bearer $api_token")
 
-echo "Current IP is $ip"
+record_id=$(jq -r '{"result"}[] | .[0] | .id' <<< $record_data)
+cf_ip=$(jq -r '{"result"}[] | .[0] | .content' <<< $record_data)
+ext_ip=$(curl -s -X GET -4 https://ifconfig.co)
 
-if host $dnsrecord 1.1.1.1 | grep "has address" | grep "$ip"; then
-        echo "$dnsrecord is currently set to $ip; no changes needed"
-        exit
+if [[ $cf_ip != $ext_ip ]]; then
+	result=$(curl -s \
+		-X PUT "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records/$record_id" \
+		-H "Content-Type: application/json" \
+		-H "X-Auth-Email: $email" \
+		-H "Authorization: Bearer $api_token" \
+		--data "{\"type\":\"A\",\"name\":\"$dns_record\",\"content\":\"$ext_ip\",\"ttl\":1,\"proxied\":false}" \
+		| jq .success)
+	if [[ $result == "true" ]]; then
+		echo "$dns_record updated to: $ext_ip"
+		exit 0
+	else
+		echo "$dns_record update failed"
+		exit 1
+	fi
+else
+	echo "$dns_record already up do date"
+	exit 0
 fi
-
-# if here, the dns record needs updating
-
-# get the zone id for the requested zone
-zoneid=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$zone&status=active" \
-        -H "Authorization: Bearer $cloudflare_token" \
-        -H "Content-Type: application/json" | jq -r '{"result"}[] | .[0] | .id')
-
-echo "Zoneid for $zone is $zoneid"
-
-# get the dns record id
-dnsrecordid=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zoneid/dns_records?type=A&name=$dnsrecord" \
-        -H "Authorization: Bearer $cloudflare_token" \
-        -H "Content-Type: application/json" | jq -r '{"result"}[] | .[0] | .id')
-
-echo "DNSrecordid for $dnsrecord is $dnsrecordid"
-
-# update the record
-curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zoneid/dns_records/$dnsrecordid" \
-        -H "Authorization: Bearer $cloudflare_token" \
-        -H "Content-Type: application/json" \
-        --data "{\"type\":\"A\",\"name\":\"$dnsrecord\",\"content\":\"$ip\",\"ttl\":1,\"proxied\":false}" | jq
